import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactScan } from "@/components/react-scan";
import Link from "next/link";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4">
          <Link href="/" className="text-blue-500 hover:text-blue-700">
            Home
          </Link>
        </nav>
        <ReactScan />
        {children}
      </body>
    </html>
  );
}
